alter table STOCKS_PORTFOLIO_INCOME add constraint FK_STOCKS_PORTFOLIO_INCOME_PORTFOLIO foreign key (PORTFOLIO_ID) references STOCKS_PORTFOLIO(ID);
create index IDX_STOCKS_PORTFOLIO_INCOME_PORTFOLIO on STOCKS_PORTFOLIO_INCOME (PORTFOLIO_ID);
