alter table STOCKS_OPERATION add constraint FK_STOCKS_OPERATION_PORTFOLIO foreign key (PORTFOLIO_ID) references STOCKS_PORTFOLIO(ID);
create index IDX_STOCKS_OPERATION_PORTFOLIO on STOCKS_OPERATION (PORTFOLIO_ID);
