alter table STOCKS_ACCOUNT add constraint FK_STOCKS_ACCOUNT_ACCOUNT_TYPE foreign key (ACCOUNT_TYPE_ID) references STOCKS_ACCOUNT_TYPE(ID);
create index IDX_STOCKS_ACCOUNT_ACCOUNT_TYPE on STOCKS_ACCOUNT (ACCOUNT_TYPE_ID);
