-- begin STOCKS_OPERATION
alter table STOCKS_OPERATION add constraint FK_STOCKS_OPERATION_PORTFOLIO foreign key (PORTFOLIO_ID) references STOCKS_PORTFOLIO(ID)^
alter table STOCKS_OPERATION add constraint FK_STOCKS_OPERATION_STOCK foreign key (STOCK_ID) references STOCKS_STOCK(ID)^
create index IDX_STOCKS_OPERATION_PORTFOLIO on STOCKS_OPERATION (PORTFOLIO_ID)^
create index IDX_STOCKS_OPERATION_STOCK on STOCKS_OPERATION (STOCK_ID)^
-- end STOCKS_OPERATION
-- begin STOCKS_STOCK
create unique index IDX_STOCKS_STOCK_UK_NAME on STOCKS_STOCK (NAME) where DELETE_TS is null ^
create unique index IDX_STOCKS_STOCK_UK_CODE on STOCKS_STOCK (CODE) where DELETE_TS is null ^
-- end STOCKS_STOCK
-- begin STOCKS_PORTFOLIO_INCOME
alter table STOCKS_PORTFOLIO_INCOME add constraint FK_STOCKS_PORTFOLIO_INCOME_PORTFOLIO foreign key (PORTFOLIO_ID) references STOCKS_PORTFOLIO(ID)^
create index IDX_STOCKS_PORTFOLIO_INCOME_PORTFOLIO on STOCKS_PORTFOLIO_INCOME (PORTFOLIO_ID)^
-- end STOCKS_PORTFOLIO_INCOME
